### PR TITLE
EliaDS.ipynb solution to lab 1

### PR DESCRIPTION
**Pull request by EliaDS99**
Hi, I have never used GitHub before so I'm not sure that I correctly put the file EliaDS.ipynb here. Please let me know if there is something wrong.

### CODE REVIEW

**Comment by bardhprenkaj** [comment]
The file you uploaded needs to be inside the folder **2023_22/lab1/solutions**

**Comment by EliaDS99** [comment]
Hi, did you receive my new upload inside the folder of solutions?

Il giorno lunedì 11 dicembre 2023, Bardh Prenkaj ***@***.***>
ha scritto:

**Comment by bardhprenkaj** [comment]
No. it's still in the parent folder. Open a new one again. I'm closing this pull request as for now.

**Comment by EliaDS99** [comment]
sorry to bother you, do you see it now in the right folder?


Il giorno mar 12 dic 2023 alle ore 11:41 Bardh Prenkaj <
***@***.***> ha scritto:

**Pull request closed without merging**
