### PR TITLE
Solution Lukas Weigmann

### PR DESCRIPTION
**Pull request by Lukas0912**

### CODE REVIEW

**Review by bardhprenkaj — CHANGES_REQUESTED** [review]
Please merge the remote repository on your local one since the folder 2022_23 doesn't exist anymore. Save your solution somewhere else to avoid losing it during the merge procedure.

Please submit only 1 file under the 2023/lab3/submissions folder.

**Comment by Lukas0912** [comment]
My fork should be using the newest folder structure as well. I hope it's alright like this!

**Comment by bardhprenkaj** [comment]
It's cool that you tried a convolution neural network. However, the exercise required playing with fully connected layers (i.e., torch.nn.Linear). Also, since you delved into CNNs, the hidden layers should've been done on the convolutional operations and not on the last linear layers. Moreover, you didn't do any hyperparameter optimization using optuna or wandb. I'll evaluate your solution, but I won't merge it into the main repo.

**Comment by bardhprenkaj** [comment]
It's cool that you tried a convolution neural network. However, the exercise required playing with fully connected layers (i.e., torch.nn.Linear). Also, since you delved into CNNs, the hidden layers should've been done on the convolutional operations and not on the last linear layers. Moreover, you didn't do any hyperparameter optimization using optuna or wandb. I'll evaluate your solution, but I won't merge it into the main repo.

**Pull request closed without merging**
